---
name: 'Weekly PR Summary'
description: 'Summarize Pull Requests and optionally create a discussion'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  repo_name:
    description: 'Repository name (owner/repo)'
    required: true
  category:
    description: 'Discussion category (optional)'
    required: false
  title_template:
    description: 'Discussion title template (optional)'
    required: false
    default: 'Recent activity (from {start} to {end})'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ${{ github.action_path }}/.python-version
    - name: Install the package and its dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
      shell: bash
    - name: Run PR summary script
      run: summarize-repo-activity
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_REPO_NAME: ${{ inputs.repo_name }}
        INPUT_CATEGORY: ${{ inputs.category }}
