---
name: 'Weekly PR Summary'
description: 'Summarize Pull Requests and optionally create a discussion'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  repo_name:
    description: 'Repository name (owner/repo)'
    required: true
  category:
    description: 'Discussion category (optional)'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: Run PR summary script
      run: python summarize_prs.py
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_REPO_NAME: ${{ inputs.repo_name }}
        INPUT_CATEGORY: ${{ inputs.category }}
