---
name: 'Weekly PR Summary'
description: 'Summarize Pull Requests and optionally create a discussion'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  repo_name:
    description: 'Repository name (owner/repo)'
    required: true
  category:
    description: 'Discussion category'
    required: false
    default: 'Announcements'
  project_name:
    description: 'Name of the project (to override the repository name)'
    required: false
  model:
    description: 'LLM model to use for generating the summary'
    required: false
    default: 'openrouter/anthropic/claude-3.5-sonnet:beta'
  verbose:
    description: 'Increase verbosity (0 for no verbose output, 1 for INFO, 2 for DEBUG)'
    required: false
    default: '0'
  dry_run:
    description: "Dry run mode: don't post the discussion"
    required: false
    default: 'false'
  start:
    description: 'Start date for the summary (format: YYYY-MM-DD)'
    required: false
  output_content:
    description: 'Path to render the GitHub activity report used as input for the LLM'
    required: false
  output:
    description: 'Path to output the AI summary'
    required: false
  output_prompt:
    description: 'Path to output the LLM prompt'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ${{ github.action_path }}/.python-version
    - name: Install the package and its dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ${{ github.action_path }}
      shell: bash
    - name: Run PR summary script
      run: summarize-repo-activity
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_REPO_NAME: ${{ inputs.repo_name }}
        INPUT_CATEGORY: ${{ inputs.category }}
