---
name: 'Weekly PR Summary'
description: 'Summarize Pull Requests and optionally create a discussion'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  repo-name:
    description: 'Repository name (owner/repo)'
    required: true
  category:
    description: 'Discussion category'
    required: false
    default: 'Announcements'
  project-name:
    description: 'Name of the project (to override the repository name)'
    required: false
  model:
    description: >
      LLM model to use for generating the summary.
      The default model requires the llm-openrouter extra package.
      Install it by setting extra-packages: 'llm-openrouter'.
      For other LLM providers, install the corresponding llm plugin
      (e.g., 'llm-gemini' for Google's Gemini models) and specify the model name.
    required: false
    default: 'openrouter/anthropic/claude-3.5-sonnet:beta'
  verbose:
    description: 'Increase verbosity (0 for no verbose output, 1 for INFO, 2 for DEBUG)'
    required: false
    default: '0'
  dry-run:
    description: "Dry run mode: don't post the discussion"
    required: false
    default: 'false'
  start:
    description: 'Start date for the summary (format: YYYY-MM-DD)'
    required: false
  output-content:
    description: 'Path to render the GitHub activity report used as input for the LLM'
    required: false
  output:
    description: 'Path to output the AI summary'
    required: false
  output-prompt:
    description: 'Path to output the LLM prompt'
    required: false
  extra-packages:
    description: >
      Additional Python packages to install (space-separated).
      For the default model, set this to 'llm-openrouter'.
      For other LLM providers, include the corresponding llm plugin
      (e.g., 'llm-gemini' for Google's Gemini models).
    required: false
    default: ''
  extra-commands:
    description: >
      Additional shell commands to run before the summary script.
      Useful for debugging purposes.
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ${{ github.action_path }}/.python-version

    - name: Collect API keys and plugins
      run: |
        import json, os
        table = """
              llm-openrouter openrouter ${{ env.OPENROUTER_KEY }}
              llm-claude-3   claude     ${{ env.CLAUDE_KEY }}
        """ # PLUGIN         PROVIDER   KEY
        entries = [line.split() for line in table.splitlines() if line.strip()]
        plugins = ' '.join(entry[0] for entry in entries)
        keys = [entry[1:] for entry in entries if len(entry) == 3]
        with open(os.getenv('GITHUB_ENV'), 'w') as env:
            print(f'PLUGINS="{plugins}"', file=env)
            print(f'KEYS="{json.dumps(keys)}"', file=env)
      shell: python

    - name: Install the package and its dependencies
      run: |
        python -m pip install --upgrade pip
        pip install \
          ${{ github.action_path }} \
          ${{ inputs.extra-packages }} \
          ${{ env.PLUGINS }}
      shell: bash

    - name: Store API keys in llm key registry
      run: |
        import json, os, subprocess
        for provider, key in json.loads(os.getenv('KEYS')):
            subprocess.run(['llm', 'keys', 'set', provider, '--value', key])
      shell: python

    - name: Run extra commands
      if: inputs.extra-commands != ''
      run: ${{ inputs.extra-commands }}
      shell: bash

    - name: Run PR summary script
      run: summarize-repo-activity
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_REPO_NAME: ${{ inputs.repo-name }}
        INPUT_CATEGORY: ${{ inputs.category }}
        INPUT_PROJECT_NAME: ${{ inputs.project-name }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_VERBOSE: ${{ inputs.verbose }}
        INPUT_DRY_RUN: ${{ inputs.dry-run }}
        INPUT_START: ${{ inputs.start }}
        INPUT_OUTPUT_CONTENT: ${{ inputs.output-content }}
        INPUT_OUTPUT: ${{ inputs.output }}
        INPUT_OUTPUT_PROMPT: ${{ inputs.output-prompt }}
        INPUT_EXTRA_PACKAGES: ${{ inputs.extra-packages }}
