---
name: Weekly Activity Summary
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 * * MON'  # Run every Monday at 00:00 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PR Summary Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-name: ${{ github.repository }}
          project-name: "${{ github.repository }}"
          category: 'Announcements'  # Optional: Specify the discussion category
          model: "openrouter/anthropic/claude-3.5-sonnet:beta"
