---
name: Test model APIs
on:  # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:  # Allow manual triggering

jobs:
  openai:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: OpenAI GPT-4o Mini
        uses: ./  # Use the local action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-name: ${{ github.repository }}
          project-name: "Test OpenAI API"
          category: "Announcements"
          model: "gpt-4o-mini"
          dry-run: true
          start: "2024-08-10"
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
  openrouter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: OpenRouter Llama 3.2 11B Vision Instruct (free)
        uses: ./  # Use the local action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-name: ${{ github.repository }}
          project-name: "Test OpenRouter API"
          category: "Announcements"
          model: "openrouter/meta-llama/llama-3.2-11b-vision-instruct:free"
          dry-run: true
          start: "2024-08-10"
        env:
          OPENROUTER_KEY: ${{ secrets.OPENROUTER_KEY }}
  claude:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Anthropic Claude 3 Haiku
        uses: ./  # Use the local action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-name: ${{ github.repository }}
          project-name: "Test Anthropic Claude 2 Haiku API"
          category: "Announcements"
          model: "claude-3-haiku"
          dry-run: true
          start: "2024-08-10"
        env:
          CLAUDE_KEY: ${{ secrets.CLAUDE_KEY }}
