---
name: Weekly PR Summary
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 * * MON'  # Run every Monday at 00:00 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  summarize-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Run PR Summary Action
        uses: akaihola/repo-summary-post@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_name: ${{ github.repository }}
          category: 'General'  # Optional: Specify the discussion category
