name: Weekly PR Summary
on:
  schedule:
    - cron: '0 0 * * MON'  # Run every Monday at 00:00 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  summarize-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run PR summary script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.repository }}
        run: python .github/scripts/summarize_prs.py
